apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncope
spec:
  replicas: 2
  selector:
    matchLabels:
      app: syncope
  template:
    metadata:
      labels:
        app: syncope
    spec:
      containers:
        - name: syncope
          image: apache/syncope:3.0.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: KEYMASTER_ADDRESS
              value: pippo
            - name: KEYMASTER_USERNAME
              value: pippo
            - name: KEYMASTER_PASSWORD
              value: pippo
            - name: SERVICE_DISCOVERY_ADDRESS
              value: pippo
            - name: ANONYMOUS_USER
              value: pippo
            - name: ANONYMOUS_KEY
              value: pippo
